AWSTemplateFormatVersion: '2010-09-09'
Description: Set up a personal Jitsi meet server as an EC2 instance.
  See https://github.com/jtrefke/jitsi-meet-video-conference-server

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Server configuration'
        Parameters:
          - FullyQualifiedHostname
          - InstanceSize
          - InstanceMaximumHourlyPrice
      - Label:
          default: 'SSL certificate (optional, one recommended)'
        Parameters:
          - SslLetsencryptEmail
          - SslCertificateCrt
          - SslCertificateKey
      - Label:
          default: 'Jitsi meeting authentication (optional, disabled when empty)'
        Parameters:
          - MeetingCreatorUsername
          - MeetingCreatorPassword
      - Label:
          default: 'Jitsi customizations (optional)'
        Parameters:
          - JitsiEnableWelcomePage
          - JitsiRequireDisplayName
          - JitsiStartAudioMuted
          - JitsiStartVideoMuted
          - JitsiDisableAudioLevels
          - JitsiWatermarkImageUrl
      - Label:
          default: 'Service schedule (optional)'
        Parameters:
          - InstanceStartupTimes
          - InstanceShutdownTimes
      - Label:
          default: 'Hooks to invoke pre-install, post-install/reboot (optional, disabled when empty)'
        Parameters:
          - HooksPreInstall
          - HooksCustomize
          - HooksPostInstall
          - HooksWaitTime
      - Label:
          default: 'Developer options'
        Parameters:
          - InstallerVersion
          - SshKeyName
      - Label:
          default: 'Work in progess / experimental'
        Parameters:
          - DialinSipAccountUid
          - DialinSipPassword
          - DialinSipPhoneNumbers

    ParameterLabels:
      FullyQualifiedHostname:
        default: '* Hostname'
      SslLetsencryptEmail:
        default: 'Letsencrypt SSL certificate email'
      SslCertificateCrt:
        default: 'SSL certificate'
      SslCertificateKey:
        default: 'SSL certificate key'
      MeetingCreatorUsername:
        default: 'Meeting creator username'
      MeetingCreatorPassword:
        default: 'Meeting creator password'
      HooksPreInstall:
        default: 'Pre install hook'
      HooksPostInstall:
        default: 'Post install hook'
      HooksCustomize:
        default: 'Customization hook'
      HooksWaitTime:
        default: 'Wait time'
      InstanceSize:
        default: '* Instance Size'
      InstanceMaximumHourlyPrice:
        default: 'Maximum Hourly Price'
      InstanceStartupTimes:
        default: 'Scheduled startup times'
      InstanceShutdownTimes:
        default: 'Scheduled shutdown times'
      JitsiWatermarkImageUrl:
        default: 'Watermark image URL'
      JitsiEnableWelcomePage:
        default: 'Enable welcome page'
      JitsiDisableAudioLevels:
        default: 'Disable audio level indicators'
      JitsiStartAudioMuted:
        default: 'Mute audio'
      JitsiStartVideoMuted:
        default: 'Mute video'
      JitsiRequireDisplayName:
        default: 'Require display name'
      DialinSipAccountUid:
        default: 'SIP account UID'
      DialinSipPassword:
        default: 'SIP password'
      DialinSipPhoneNumbers:
        default: 'SIP phone numbers'
      InstallerVersion:
        default: 'Jitsi Installer Version'
      SshKeyName:
        default: 'EC2 SSH key name'

Parameters:
  FullyQualifiedHostname:
    Description: Fully qualified hostname (e.g. meet.example.com)
    Type: String
    MinLength: 4
    MaxLength: 255
    ConstraintDescription: Must be between 4 and 255 characters.
  MeetingCreatorUsername:
    Description: Username for the meeting creator account
    Type: String
    MinLength: 0
    MaxLength: 255
  MeetingCreatorPassword:
    Description: Password for the meeting creator account
    NoEcho: true
    Type: String
    MinLength: 0
    MaxLength: 255
  SslLetsencryptEmail:
    Description: E-mail address for retrieving SSL certificate from letsencrypt.org
    Type: String
    MaxLength: '255'
    ConstraintDescription: Must be less than 255 characters.
  SslCertificateCrt:
    Description: Existing SSL certificate (gzipped and base64 encoded (see "helpers/encode-file-parameter"))
    Type: String
    NoEcho: true
  SslCertificateKey:
    Description: Existing SSL certificate key (gzipped and base64 encoded (see "helpers/encode-file-parameter"))
    Type: String
    NoEcho: true
  HooksPreInstall:
    Description: Regular URL or encoded script (see "helpers/encode-file-parameter")) to invoke before installation starts
    Type: String
  HooksCustomize:
    Description: Encoded script (see "helpers/encode-file-parameter")) to run or regular URL to invoke after Jisti install
    Type: String
  HooksPostInstall:
    Description: Regular URL or encoded script (see "helpers/encode-file-parameter")) to invoke after setup is finished and at each reboot
    Type: String
  HooksWaitTime:
    Description: Time to wait after invoking hooks (in seconds)
    Type: Number
    Default: 121
  JitsiWatermarkImageUrl:
    Description: Custom watermark image URL that is overlayed in top left corner
    Type: String
  JitsiEnableWelcomePage:
    Description: Enable welcome page at root path
    Default: true
    Type: String
    AllowedValues: [true, false]
  JitsiDisableAudioLevels:
    Description: Disable display of audio level indicators for participants
    Default: false
    Type: String
    AllowedValues: [true, false]
  JitsiStartAudioMuted:
    Description: Mute audio for new participants after the nth participant enters
    Type: Number
    Default: 4
    MinValue: 0
    MaxValue: 1000
  JitsiStartVideoMuted:
    Description: Mute video for new participants after the nth participant enters
    Type: Number
    Default: 8
    MinValue: 0
    MaxValue: 1000
  JitsiRequireDisplayName:
    Description: Require participant to enter a display name
    Type: String
    AllowedValues: [true, false]
    Default: true
  DialinSipAccountUid:
    Description: Account UID for SIP account (e.g. 453252@provider.net)
    Type: String
    MinLength: 0
    MaxLength: 255
  DialinSipPassword:
    Description: Password for SIP account
    NoEcho: true
    Type: String
    MinLength: 0
    MaxLength: 255
  DialinSipPhoneNumbers:
    Description: Password for SIP account
    Type: String
    AllowedPattern: '([^,]+((,[^,]+)+)?)?'
  InstanceMaximumHourlyPrice:
    Description: Maximum price per hour to bid on spot market; if not provided, default on-demand pricing will be used.
    Type: String
    AllowedPattern: '([0-9]\.[0-9]+|^$)'
    ConstraintDescription: 'Must be a dot-separated decimal number'
  InstanceStartupTimes:
    Description: Schedule regular server start in cron syntax (e.g. "3 7 * * 1-5" for "Mon-Fri at 7:03am")
    Type: String
    AllowedPattern: "(.+ .+ .+ .+ .+|^$)"
  InstanceShutdownTimes:
    Description: Schedule regular server shutdown in cron syntax (e.g. "0 19 26 * *" for "every 26th of the month at 7:00pm")
    Type: String
    AllowedPattern: "(.+ .+ .+ .+ .+|^$)"
  InstallerVersion:
    Type: String
    MinLength: 5
    Description: Version of installer (release tag) or 'latest'
    Default: latest
  SshKeyName:
    Type: String
    Description: Existing keyname; to be used for debugging purposes only

  InstanceSize:
    Description: EC2 instance type
    Type: String
    Default: Small.t3.small
    AllowedValues:
    - Micro.t3.micro
    - Small.t3.small
    - Medium.t3.medium
    - Large.m5.large
    - XtraLarge.m5.xlarge
    - XtraXtralarge.m5.2xlarge

Mappings:
  AWSInstanceType2Arch:
    Micro.t3.micro:
      InstanceType: t3.micro
    Small.t3.small:
      InstanceType: t3.small
    Medium.t3.medium:
      InstanceType: t3.medium
    Large.m5.large:
      InstanceType: m5.large
    XtraLarge.m5.xlarge:
      InstanceType: m5.xlarge
    XtraXtralarge.m5.2xlarge:
      InstanceType: m5.2xlarge
  AWSRegionArch2AMI:
    # Ubuntu AMIs per region as of 2020-04-26 20:54:48 UTC
    # Data from: https://cloud-images.ubuntu.com/locator/ec2/releasesTable?_=1587934487
    # Criteria: name='bionic', version='18.04 LTS', arch='amd64', instance_type='hvm:ebs-ssd', aki_id='hvm'
    af-south-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0914f03407aa25fb8
    ap-east-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-c790d6b6
    ap-northeast-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0278fe6949f6b1a06
    ap-northeast-2:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-00edfb46b107f643c
    ap-northeast-3:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-00eac2261db3c9df5
    ap-south-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0b44050b2d893d5f7
    ap-southeast-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0f7719e8b7ba25c61
    ap-southeast-2:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-04fcc97b5f6edcd89
    ca-central-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0edd51cc29813e254
    cn-north-1:
      # Ubuntu 18.04 LTS (release 20200323)
      HVM64: ami-0071f6f4df15863cc
    cn-northwest-1:
      # Ubuntu 18.04 LTS (release 20200323)
      HVM64: ami-0a22b8776bb32836b
    eu-central-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0e342d72b12109f91
    eu-north-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-050981837962d44ac
    eu-west-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0701e7be9b2a77600
    eu-west-2:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0eb89db7593b5d434
    eu-west-3:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-08c757228751c5335
    me-south-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-051274f257aba97f9
    sa-east-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-077d5d3682940b34a
    us-east-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-085925f297f89fce1
    us-east-2:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-07c1207a9d40bc3bd
    us-west-1:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-0f56279347d2fa43e
    us-west-2:
      # Ubuntu 18.04 LTS (release 20200408)
      HVM64: ami-003634241a8fcdec0

Conditions:
  SshKeyNameProvided: !Not [!Equals [ !Ref SshKeyName, "" ]]
  InstanceMaximumHourlyPriceProvided: !Not [!Equals [ !Ref InstanceMaximumHourlyPrice, "" ]]
  ScheduledInstanceStartEnabled: !Not [!Equals [ !Ref InstanceStartupTimes, "" ]]
  ScheduledInstanceShutdownEnabled: !Not [!Equals [ !Ref InstanceShutdownTimes, "" ]]

Resources:
  JitsiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Jitsi Security Groups
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 4443
        ToPort: 4443
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: 10000
        ToPort: 20000
        CidrIp: 0.0.0.0/0

  JitsiAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: 1
        PauseTime: "PT7M"
        # WaitOnResourceSignals: true
        SuspendProcesses:
        - HealthCheck
        - ReplaceUnhealthy
        - AZRebalance
        - AlarmNotification
        - ScheduledActions
    Properties:
      AvailabilityZones:
        Fn::GetAZs:
          Ref: "AWS::Region"
      LaunchConfigurationName:
        Ref: "JitsiInstanceLaunchConfig"
      MaxSize: "2"
      MinSize: "1"
      TerminationPolicies:
        - NewestInstance
        - Default
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName
        PropagateAtLaunch: true
      - Key: Application
        Value: Jitsi
        PropagateAtLaunch: true

  ScheduledInstanceStart:
    Type: AWS::AutoScaling::ScheduledAction
    Condition: ScheduledInstanceStartEnabled
    Properties:
      AutoScalingGroupName:
        Ref: "JitsiAutoScalingGroup"
      MaxSize: 2
      MinSize: 1
      Recurrence:
        Ref: InstanceStartupTimes
  ScheduledInstanceShutdown:
    Type: AWS::AutoScaling::ScheduledAction
    Condition: ScheduledInstanceShutdownEnabled
    Properties:
      AutoScalingGroupName:
        Ref: "JitsiAutoScalingGroup"
      MaxSize: 0
      MinSize: 0
      Recurrence:
        Ref: InstanceShutdownTimes

  WaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  WaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: JitsiAutoScalingGroup
    Properties:
      Handle:
        Ref: WaitHandle
      Timeout: "4200"

  JitsiInstanceLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceMonitoring: false
      KeyName:
        Fn::If:
        - SshKeyNameProvided
        - Ref: SshKeyName
        - Ref: AWS::NoValue
      SpotPrice:
        Fn::If:
        - InstanceMaximumHourlyPriceProvided
        - Ref: InstanceMaximumHourlyPrice
        - Ref: AWS::NoValue

      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - HVM64
      SecurityGroups:
      - Ref: JitsiSecurityGroup
      InstanceType:
        Fn::FindInMap:
        - AWSInstanceType2Arch
        - Ref: InstanceSize
        - InstanceType
      UserData:
        Fn::Base64: !Join
          - ''
          - - |
              #!/bin/bash
              # script is placed in /var/lib/cloud/instances/*/scripts/part-*
              # logs can be found in /var/log/cloud-init-output.log
              ensure_python2_active() {
                major_python_version=$(python -V | grep -Eo "[0-9]" | head -1)
                [ "${major_python_version}" != "2" ] || return 0

                if ! command -v "python2" >/dev/null 2>&1; then
                  apt install -y python-minimal || true
                  apt install -y python2 || true
                fi

                if command -v "python2" >/dev/null 2>&1; then
                  ln -sf $(command -v "python2") /usr/bin/python
                fi
              }

              ensure_cfn_signal_installed() {
                ! command -v cfn-signal>/dev/null 2>&1 || return 0

                # prepare instance with AWS CloudFormation utilities
                # based on https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html#cfn-helper-scripts-reference-downloads
                ensure_python2_active
                apt install -y python-requests || true
                apt install -y python-setuptools || true
                (
                  cd "$(mktemp -d)"
                  curl -sL "https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz" | \
                    tar -xzf -
                  cd ./*
                  python setup.py install
                  ln -sf /root/aws-cfn-bootstrap-latest/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
                )
              }

              export DEBIAN_FRONTEND=noninteractive
              apt update -y
              command -v curl >/dev/null 2>&1 || apt install -y curl

              ensure_cfn_signal_installed

            - !Sub |
              # Ensure to signal exit to CloudFormation
              trap 'cfn_signal_wait_exit $?' EXIT
              set -e

              cfn_signal_wait_exit() {
                set +eu || true
                local reason="SUCCESS"
                if [ "$1" != "0" ]; then
                  reason="$(tail -c 100 /var/log/cloud-init-output.log | tr -d "\n" || true)"
                  [ -n "$reason" ] || reason="FAILURE"
                fi

                cfn-signal -e "$1" --stack "${AWS::StackName}" --region "${AWS::Region}" \
                  --reason "$reason" "${WaitHandle}"
              }

            - !If
              - SshKeyNameProvided
              - FIREWALL_ENABLE_SSH=true
              - FIREWALL_ENABLE_SSH=false
            - !Sub |

              INSTALLER_VERSION='${InstallerVersion}'

              # create Jitsi installer configuration using provided parameters
              recode_parameter() {
                [ -z "$1" ] || echo "$1" | base64 -d | zcat - | base64 | tr -d "\n"
              }
              starts_with_curl_url_scheme() {
                <<<"$1" grep -Eiq "^(dict|file|ftps?|gopher|https?|imaps?|ldaps?|mqtt|pop3s?|rtmp|rtsp|scp|sftp|smbs?|smtps?|telnet|tftp)://"
              }
              keep_url_or_recode() {
                starts_with_curl_url_scheme "$1" && echo "$1" || recode_parameter "$1"
              }

              INSTALL_DIR="$(mktemp -d)"

              cat << EOF > "$INSTALL_DIR/jitsiinstallrc"
              FULLY_QUALIFIED_HOSTNAME='${FullyQualifiedHostname}'
              SSL_LETSENCRYPT_EMAIL='${SslLetsencryptEmail}'
              SSL_CERTIFICATE_CRT="$(recode_parameter '${SslCertificateCrt}')"
              SSL_CERTIFICATE_KEY="$(recode_parameter '${SslCertificateKey}')"
              FIREWALL_ENABLE_SSH="$FIREWALL_ENABLE_SSH"
              HOOKS_PRE_INSTALL="$(keep_url_or_recode '${HooksPreInstall}')"
              HOOKS_POST_INSTALL="$(keep_url_or_recode '${HooksPostInstall}')"
              HOOKS_CUSTOMIZE="$(keep_url_or_recode '${HooksCustomize}')"
              HOOKS_WAIT_TIME='${HooksWaitTime}'
              JITSI_MEETING_CREATOR_USERNAME='${MeetingCreatorUsername}'
              JITSI_MEETING_CREATOR_PASSWORD='${MeetingCreatorPassword}'
              JITSI_WATERMARK_IMAGE_URL='${JitsiWatermarkImageUrl}'
              JITSI_ENABLE_WELCOME_PAGE='${JitsiEnableWelcomePage}'
              JITSI_DISABLE_AUDIO_LEVELS=${JitsiDisableAudioLevels}
              JITSI_START_AUDIO_MUTED=${JitsiStartAudioMuted}
              JITSI_START_VIDEO_MUTED=${JitsiStartVideoMuted}
              JITSI_REQUIRE_DISPLAY_NAME=${JitsiRequireDisplayName}
              DIALIN_SIP_ACCOUNT_UID='${DialinSipAccountUid}'
              DIALIN_SIP_PASSWORD='${DialinSipPassword}'
              DIALIN_PSTN_NUMBERS='${DialinSipPhoneNumbers}'
              EOF
            - |

              # install Jitsi with latest automated installer
              INSTALLER_URL="https://api.github.com/repos/jtrefke/jitsi-meet-video-conference-installer/releases/latest"
              if [ "${INSTALLER_VERSION:-}" != "latest" ]; then
                INSTALLER_URL="https://api.github.com/repos/jtrefke/jitsi-meet-video-conference-installer/releases/tags/${INSTALLER_VERSION}"
              fi

              INSTALLER_TARBALL=$(curl -sL "${INSTALLER_URL}" | sed -En 's/.*tarball_url.+(http[^"]+).*/\1/p')
              curl -sL "${INSTALLER_TARBALL}" | tar -xzf - -C "${INSTALL_DIR}"

              mv "${INSTALL_DIR}/jtrefke-jitsi-meet-video-conference-installer"*/* "${INSTALL_DIR}"
              chmod +x "${INSTALL_DIR}/installer/install-jitsi.sh"

              "${INSTALL_DIR}/installer/install-jitsi.sh"
              rm -rf "${INSTALL_DIR}"

Outputs:
  JitsiServerHostname:
    Description: Find Jitsi meet install at
    Value: !Sub 'https://${FullyQualifiedHostname}'
  Info:
    Description: |
      Allow a few minutes after launch until the setup has finished.

      Client Downloads:
      Android: https://play.google.com/store/apps/details?id=org.jitsi.meet /
      iOS: https://itunes.apple.com/us/app/jitsi-meet/id1165103905 /
      Slack: https://slack.com/oauth/authorize?client_id=116888949298.122751011265&scope=bot,commands /
      Desktop: https://desktop.jitsi.org/Main/Download#stableline

      Find more info about Jitsi at https://jitsi.org/
    Value: Notes
